server:
  port: 8084
spring:
  application:
    name: alibaba-sentinel-datasource-nacos
  # sentinel dashboard
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080                         # 数配置sentinel dashboard的访问地址
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848                   # nacos访问地址
            data-id: ${spring.application.name}-sentinel  # nacos中存储规则的dataid
            group-id: DEFAULT_GROUP                       # nacos中存储规则的groupId
            rule-type: flow     # 该参数是spring cloud alibaba升级到0.2.2之后增加的配置，用来定义存储的规则类型

# 所有的规则类型可查看枚举类：org.springframework.cloud.alibaba.sentinel.datasource.RuleType，每种规则的定义格式可以通过各枚举值中定义的规则对象来查看，比如限流规则可查看：com.alibaba.csp.sentinel.slots.block.flow.FlowRule
# 这里对于dataId使用了${spring.application.name}变量，这样可以根据应用名来区分不同的规则配置。