server:
  port: 8087
spring:
  application:
    name: alibaba-dubbo-server      # 名称

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos 服务地址

# 覆盖相同bean名称（如果使用Spring Boot 2.1及更高版本时候）
#  main:
#    allow-bean-definition-overriding=true: true

# dubbo
dubbo:
  scan:
    base-packages: com.ityouzi.server     # 指定Dubbo服务实现类的扫描基准包
  protocol:
    name: dubbo # 协议名称
    port: -1    # -1 表示自增端口，从 20880 开始
  registry:
    address: spring-cloud://localhost # Dubbo 服务注册中心配置，其中子属性 address 的值 “spring-cloud://localhost”，说明挂载到 Spring Cloud 注册中心